[package]
name = "autodiff"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["examples/*"]

[dependencies]
nalgebra = { version = "0.32.2", features = ["rand", "serde"] }
serde = { version = "1.0.162", features = ["derive"] }
