[package]
name = "mnist_classifier"
version = "0.1.0"
edition = "2021"

[dependencies]
autodiff = { path = "../.." }
bincode = "1.3.3"
minifb = "0.24.0"
mnist = { version = "0.5.0", features = ["download"] }
